### ISSUE TITLE
功能请求：增加 DNS Name / subjectAltName 检测

### ISSUE THREAD

**Issue by SeaHOH** [johnsonz/go-checkiptools#1]
请求功能：
1、域名提取从 **CommonName** 字段改为使用 **subjectAltName** 扩展字段，可得到更多域名。
2、域名不按完整名称匹配，改为从域名开头匹配，更加方便灵活。
* 如：`*.google.jp` 可以被 `*.google.` 匹配

影响：
1、可根据自身需求灵活配置，扩展了应用范围，适应性更强。
2、理论上会拖慢速度，但实际应该感觉不到，性能影响可以忽略。

**Comment by johnsonz** [comment]
请问这个subjectAltName可以用DNS Name替代吗？

**Comment by SeaHOH** [comment]
好像不能，叫法是这么叫，但字段名应该是 **subjectAltName**。

**Comment by johnsonz** [comment]
学习了，看了看go的源码，发现是直接把Extensions的SubjectAltName的值解析出来了，DNSNames，而且直接查看证书的Subject Alternative Name，发现也是这种格式
```
DNS Name=aa.com
DNS Name=bb.com
```

**Comment by SeaHOH** [comment]
费得功夫应该不多，你看能搞不？
Windows 安装编译环境比较麻烦，我这种野狐禅一般就用用脚本语言，所以只能期望你啦。

**Comment by johnsonz** [comment]
https://github.com/johnsonz/go-checkiptools/releases/tag/v2.1

前缀匹配，`google.`可以匹配`google.com`或`google.com.hk`，但不会匹配`cloud.google.com`

**Comment by SeaHOH** [comment]
感谢哈，这下可以按自己的想法来自由配置了。
