### ISSUE TITLE
功能请求：根据公钥哈希值来验证谷歌证书

### ISSUE THREAD

**Issue by SeaHOH** [johnsonz/go-checkiptools#2]
[https://github.com/phuslu/goproxy/blob/ae1d225f8dd79f567cb2eb1e6cea6e0f5679cfbd/httpproxy/helpers/dialer2.go#L145-L166](url)
p 大已经实现了，我觉得完全可以照搬过来。 :smiley:

**Comment by johnsonz** [comment]
请问这种验证证书的方式有什么优势吗？p大的这一块不是用来和GAE服务器传输数据吗

**Comment by SeaHOH** [comment]
可以跳过 go 内置的验证方式，反正我们只需要验证谷歌。
应该可以减少计算量，还有确保筛选出的全是谷歌 IP。
