### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by THLIVSQAZ** [johnsonz/go-checkiptools#6]
无法启动程序，配置错误？
![screenshot_20170215-234436](https://cloud.githubusercontent.com/assets/25531652/22982428/0f644126-f3da-11e6-9809-4c45c9727816.png)

**Comment by SeaHOH** [comment]
好像是线程超限

**Comment by THLIVSQAZ** [comment]
有解决办法吗？ @SeaHOH @johnsonz

**Comment by johnsonz** [comment]
用的手机啊，你把main.json的concurrency参数值调小些试试

**Comment by THLIVSQAZ** [comment]
arm框架大部分都是手机吧。。。。。。。
能给个参考值吗？ @johnsonz

**Comment by johnsonz** [comment]
调成50 试试，还不行就继续再调小点
